user: my.name
endpoint:
  - name: repo1
    type: dummy
    api_version: 1
    url: "https://foo.bar/baz"
  - name: repo2
    type: dummy
    api_version: 2
    url: "https://hoge.hoge/fuga/fuga"
board:
  - name: team1/proj1
    alias:
      - proj1
    endpoint: repo1
    mapping:
      state:
        todo:
          asignee: my.name
          is_closed: false
          order: 3
        doing:
          label_name: doing-label
          asignee: my.name
          is_closed: false
          order: 1
        waiting:
          label_name: waiting-label
          asignee: my.name
          is_closed: false
          order: 2
        closed:
          asignee: my.name
          is_closed: true
          max_days_without_update: 14
          order: 4
  - name: team1/proj2
    alias:
      - proj2
      - proj02
    endpoint: repo1
    mapping:
      state:
        todo:
          asignee: my.name
          is_closed: false
          order: 3
        doing:
          label_name: doing-label
          asignee: my.name
          is_closed: false
          order: 1
        waiting:
          label_name: waiting-label
          asignee: my.name
          is_closed: false
          order: 2
        closed:
          asignee: my.name
          is_closed: true
          max_days_without_update: 14
          order: 4
  - name: individual
    alias:
      - mytask
    endpoint: repo2
    mapping:
      state:
        todo:
          is_closed: false
          order: 2
        now:
          label_name: doing-label
          is_closed: false
          max_days_without_update: 3
          order: 1
        fin:
          is_closed: true
          max_days_without_update: 7
          order: 3
